Improve robusteness of make-http-client-request
The following pattern causes trouble:

(in-package :interface)
(let ((web.server.url "http://localhost:8081")
      (content (apply #'format nil "x:~a" (list "a"))))
  (net.aserve.client:do-http-request (format nil "~a/crews/services" web.server.url)
			    :method "post"
			    :content-type "application/json; charset=UTF-8"
			    :external-format (ef :utf-8 :crlf)
			    :headers '(("Accept-Language" . "en-GB"))
			    :content content))
Error: Illegal content array: "x:a"

Finding from Luis B. de Oliveira:
(describe (funcall (compile nil (lambda () (apply #'format nil "x:~a" (list "a"))))))
"x:a"
[simple-base-string]

Element-type: BASE-CHAR

Tests performed:
- launch Web-Server and start it (URL: http://localhost:8081)
- launch Scheduler (SBCL image, vdev code) (don't start it, it is not necessary)
- execute the unit test above in two ways:
  - (content (apply #'format nil "x:~a" (list "a")))
  - (content (format nil "x:~a" "a"))
  Both with success.

Issue: PSCS-611
Reference: POA.37293.0
Change-Id: I7dcf19f9e2a035c86d3e2cd9a54a31fe82761919
Reviewed-on: https://gerrit.siscog/c/open-source/zaserve/+/7521
Reviewed-by: Luís Borges de Oliveira <lbo@siscog.pt>